version: '2.3'

services:
  datascience:
    image: aleksaro/data-science:latest
    command: ["/usr/bin/byobu"]
    environment:
      - NVIDIA_VISIBLE_DEVICES=0
      - USE_HTTPS=1
    ports:
      - "8888:8888"
      - "6006:6006"
    restart: always
    runtime: nvidia
    stdin_open: true
    tty: true
    volumes:
      - "~/shared:/root/shared"
